### ISSUE TITLE
Non-standerd syntax

### ISSUE THREAD

**Issue by coen22** [dschnelldavis/parse-full-name#16]
Hi I'd like to keep using this in my web project, but your'e using Node syntax

Could you replace your first line with:
export function parseFullName(

Don't know if that works in Node.js, but it does work with my PWA project.

**Comment by vandie** [comment]
Unfortunatly, what is currently in the codebase is standard syntax for NodeJS.

If you use a bundler such as [webpack](https://webpack.js.org/) or [rollup](https://rollupjs.org/guide/en/) and use somthing like [babel](https://babeljs.io/). It can ensure all libraries are using the correct syntax for you. While not a perfect solution @coen22, not all libraries are built with both ES6 & NodeJS in mind. Usually one or the other.

**Comment by coen22** [comment]
All right, but I would personally never use Javascript on the server-side.
Thanks for the script though, with a tiny change to an ES6 export it works perfectly.
